version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./api/app:/app
    working_dir: /app
    depends_on:
      - db

  front:
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./front:/app
    ports:
      - 3000:3000 

  db:
    image: postgres:14.7
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    volumes:
      - ./docker/db/initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-store:/var/lib/postgresql/data
    ports:
      - "5432:5432"
